# Generated by Django 5.0.7 on 2024-07-18 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0005_alter_reaction_object_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reaction',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='reaction',
            name='object_id',
        ),
    ]
