# Generated by Django 5.0.7 on 2024-07-19 06:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0007_reaction_content_type_reaction_object_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='participant',
        ),
        migrations.AddField(
            model_name='community',
            name='participant',
            field=models.ManyToManyField(related_name='communities_pa', to=settings.AUTH_USER_MODEL),
        ),
    ]
