# Generated by Django 5.0.7 on 2024-07-19 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0010_rename_type_reaction_types'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reaction',
            old_name='types',
            new_name='type',
        ),
    ]
