# Generated by Django 5.0.7 on 2024-07-22 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0011_rename_types_reaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='p_password',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
