# Generated by Django 5.0.7 on 2024-08-10 08:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0012_alter_community_p_password'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='administrator',
        ),
        migrations.RemoveField(
            model_name='community',
            name='participant',
        ),
        migrations.AddField(
            model_name='community',
            name='group_avatar',
            field=models.ImageField(blank=True, null=True, upload_to='static/image/'),
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('member', 'Member'), ('guest', 'Guest')], default='guest', max_length=100)),
                ('community', models.ManyToManyField(related_name='participants', to='communities.community')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
