# Generated by Django 5.0.7 on 2024-08-10 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0013_remove_community_administrator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
