# Generated by Django 5.0.7 on 2024-08-16 11:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0017_alter_participant_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='community',
            options={'permissions': [('can_delete_any_post', 'Can Delete Any Post'), ('can_delete_any_comment', 'Can Delete Any Comment'), ('can_choose_another_admin', 'Can Choose Another Admin')]},
        ),
        migrations.AddField(
            model_name='community',
            name='intro_message',
            field=models.TextField(),
        ),
        migrations.AddField(
            model_name='community',
            name='is_required_join_in_request',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='community',
            name='is_show_intro_message',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='community',
            name='is_show_rules',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='community',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='participant',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('moderator', 'Moderator'), ('member', 'Member'), ('guest', 'Guest')], default='guest', max_length=100),
        ),
        migrations.AlterField(
            model_name='participant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CommunityRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255)),
                ('description', models.TextField()),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='communities.community')),
            ],
        ),
        migrations.CreateModel(
            name='JoinInRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_in_req', to='communities.community')),
                ('sender', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
