# Generated by Django 5.0.7 on 2024-08-16 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0018_alter_community_options_community_intro_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='intro_message',
            field=models.TextField(default=''),
        ),
    ]
