# Generated by Django 5.0.7 on 2024-08-16 11:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0019_alter_community_intro_message'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='communityrule',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='joininrequest',
            options={'ordering': ['created_at']},
        ),
        migrations.RemoveField(
            model_name='community',
            name='p_password',
        ),
        migrations.AddField(
            model_name='communityrule',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='joininrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='community',
            name='intro_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='communityrule',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='joininrequest',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
