# Generated by Django 5.0.7 on 2024-08-23 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0023_remove_comment_page_post_comment_post_delete_page'),
    ]

    operations = [
        migrations.RenameField(
            model_name='community',
            old_name='is_show_intro_message',
            new_name='is_show_message',
        ),
        migrations.RenameField(
            model_name='community',
            old_name='intro_message',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='community',
            name='is_required_join_in_request',
        ),
    ]
