# Generated by Django 5.0.7 on 2024-08-23 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0024_rename_is_show_intro_message_community_is_show_message_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='community',
            old_name='is_show_rules',
            new_name='is_show_rule',
        ),
    ]
