# Generated by Django 5.0.7 on 2024-08-23 09:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0025_rename_is_show_rules_community_is_show_rule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='joininrequest',
            unique_together={('sender', 'community')},
        ),
        migrations.AlterUniqueTogether(
            name='participant',
            unique_together={('user', 'community')},
        ),
    ]
