# Generated by Django 5.0.7 on 2024-07-18 00:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('read', 'read'), ('Unread', 'Unread')], default='', max_length=100)),
                ('type', models.CharField(choices=[('Comment', 'comment'), ('Reaction', 'reaction'), ('Amin', 'admin'), ('Others', 'others')], default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
