# Generated by Django 5.0.7 on 2024-07-18 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_notification'),
        ('communities', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='From',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='communities.page'),
            preserve_default=False,
        ),
    ]
