# Generated by Django 5.0.7 on 2024-07-18 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_notification_from'),
        ('communities', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='From',
            field=models.ForeignKey(blank=True, default='notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='communities.page'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('Read', 'read'), ('Unread', 'Unread')], default='Unread', max_length=100),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('Comment', 'comment'), ('Reaction', 'reaction'), ('Amin', 'admin'), ('Others', 'others')], default='Others', max_length=100),
        ),
    ]
