# Generated by Django 5.0.7 on 2024-07-18 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_notification_from_alter_notification_status_and_more'),
        ('communities', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='From',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='communities.page'),
        ),
    ]
