# Generated by Django 5.0.7 on 2024-07-21 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_notification_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('Comment', 'comment'), ('Reaction', 'reaction'), ('Page', 'page'), ('Amin', 'admin'), ('Others', 'others')], default='Others', max_length=100),
        ),
    ]
