# Generated by Django 5.0.7 on 2024-07-16 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt', models.CharField(default='', max_length=100)),
                ('image', models.ImageField(upload_to='static/image/')),
            ],
        ),
    ]
