# Generated by Django 5.0.7 on 2024-07-16 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0007_examination_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examination',
            name='author',
        ),
        migrations.DeleteModel(
            name='MyAnswer',
        ),
    ]
