# Generated by Django 5.0.7 on 2024-07-17 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0010_alter_question_examination'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.CharField(default='', max_length=100),
        ),
    ]
