# Generated by Django 5.0.7 on 2024-07-20 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('lessons', '0011_question_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animation',
            name='section',
        ),
        migrations.RemoveField(
            model_name='content',
            name='section',
        ),
        migrations.RemoveField(
            model_name='image',
            name='section',
        ),
        migrations.AddField(
            model_name='section',
            name='content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='section',
            name='object_id',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
