# Generated by Django 5.0.7 on 2024-07-20 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0013_remove_section_content_type_remove_section_object_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='no',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
