# Generated by Django 5.0.7 on 2024-07-20 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0014_section_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='no',
            new_name='content_quantity',
        ),
    ]
