# Generated by Django 5.0.7 on 2024-07-22 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0017_examassignment_userchoice'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExamAssignment',
            new_name='Assignment',
        ),
        migrations.AddField(
            model_name='userchoice',
            name='assignment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='userchoices', to='lessons.assignment'),
            preserve_default=False,
        ),
    ]
