# Generated by Django 5.0.7 on 2024-07-24 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0019_remove_userchoice_author_assignment_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='mark',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
