# Generated by Django 5.0.7 on 2024-08-03 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0024_alter_lesson_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='content_list',
            field=models.JSONField(default=list),
        ),
    ]
