# Generated by Django 5.0.7 on 2024-08-06 13:56

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0027_remove_content_update_in_signal'),
    ]

    operations = [
        migrations.AddField(
            model_name='animation',
            name='args',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100, null=True), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='choice',
            name='title',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='title',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='section',
            name='title',
            field=models.TextField(default='', max_length=255),
        ),
    ]
