# Generated by Django 5.0.7 on 2024-08-10 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0028_animation_args_alter_choice_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='status',
        ),
    ]
