# Generated by Django 5.0.7 on 2024-08-12 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0029_remove_lesson_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='title',
        ),
        migrations.AddField(
            model_name='image',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='lesson',
            name='no',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
