# Generated by Django 5.0.7 on 2024-08-12 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0030_remove_exercise_title_image_title_lesson_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
