# Generated by Django 5.0.7 on 2024-08-16 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0031_alter_image_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['no']},
        ),
    ]
