# Generated by Django 5.0.7 on 2024-08-19 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0032_alter_lesson_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['no']},
        ),
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='no',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='choice',
            unique_together={('question', 'title')},
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('examination', 'title', 'answer')},
        ),
    ]
