# Generated by Django 5.0.7 on 2024-08-28 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0033_alter_assignment_options_alter_section_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255, unique=True)),
                ('no', models.PositiveBigIntegerField(default=0)),
                ('summary', models.TextField(default='')),
            ],
            options={
                'ordering': ['no'],
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='course',
        ),
        migrations.AlterField(
            model_name='animation',
            name='no',
            field=models.PositiveBigIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='animation',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='lessons.section'),
        ),
        migrations.AlterField(
            model_name='content',
            name='no',
            field=models.PositiveBigIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='content',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='lessons.section'),
        ),
        migrations.AlterField(
            model_name='image',
            name='no',
            field=models.PositiveBigIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='image',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='lessons.section'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='no',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='content_quantity',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='section',
            name='no',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='section',
            name='title',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='chapter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='lessons.chapter'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255, unique=True)),
                ('no', models.PositiveBigIntegerField(default=0)),
                ('theme_color', models.CharField(default='', max_length=255)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='lessons.course')),
            ],
            options={
                'ordering': ['no'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='chapter',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='lessons.topic'),
        ),
    ]
