# Generated by Django 5.0.7 on 2024-08-25 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0034_remove_lesson_course_lesson_chapter_topic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='theme_color',
            field=models.CharField(default='', max_length=255),
        ),
    ]
