# Generated by Django 5.0.7 on 2024-08-29 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0034_chapter_remove_lesson_course_alter_animation_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examination',
            name='lesson',
        ),
        migrations.AddField(
            model_name='examination',
            name='chapter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='examinations', to='lessons.chapter'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='animation',
            name='no',
            field=models.PositiveBigIntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='animation',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='lessons.section'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='no',
            field=models.PositiveBigIntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='content',
            name='no',
            field=models.PositiveBigIntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='content',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='lessons.section'),
        ),
        migrations.AlterField(
            model_name='image',
            name='no',
            field=models.PositiveBigIntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='image',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='lessons.section'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='no',
            field=models.PositiveBigIntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='section',
            name='no',
            field=models.PositiveBigIntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='topic',
            name='no',
            field=models.PositiveBigIntegerField(default=-1),
        ),
    ]
