# Generated by Django 5.0.7 on 2024-08-25 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0035_topic_theme_color'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={},
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='no',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='title',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='topic',
        ),
        migrations.AlterField(
            model_name='animation',
            name='no',
            field=models.PositiveBigIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='animation',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='lessons.section'),
        ),
        migrations.AlterField(
            model_name='content',
            name='no',
            field=models.PositiveBigIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='content',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='lessons.section'),
        ),
        migrations.AlterField(
            model_name='image',
            name='no',
            field=models.PositiveBigIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='image',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='lessons.section'),
        ),
        migrations.AlterField(
            model_name='section',
            name='content_quantity',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='section',
            name='no',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='section',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='topic',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255)),
                ('no', models.PositiveBigIntegerField(default=0)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='lessons.topic')),
            ],
            options={
                'ordering': ['no'],
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='lesson',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='lessons.chapter'),
        ),
    ]
