# Generated by Django 5.0.7 on 2024-08-25 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0036_alter_lesson_options_remove_lesson_no_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['no']},
        ),
        migrations.AddField(
            model_name='lesson',
            name='no',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lesson',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
