# Generated by Django 5.0.7 on 2024-08-30 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0036_remove_exercise_lesson_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='no',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='section',
        ),
        migrations.AddField(
            model_name='exercise',
            name='lesson',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='lessons.lesson'),
            preserve_default=False,
        ),
    ]
