# Generated by Django 5.0.7 on 2024-08-27 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0037_alter_lesson_options_lesson_no_lesson_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='summary',
            field=models.TextField(),
            preserve_default=False,
        ),
    ]
