# Generated by Django 5.0.7 on 2024-08-30 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0037_remove_exercise_no_remove_exercise_section_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='lesson',
        ),
        migrations.AddField(
            model_name='exercise',
            name='no',
            field=models.PositiveBigIntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='exercise',
            name='section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='lessons.section'),
            preserve_default=False,
        ),
    ]
