# Generated by Django 5.0.7 on 2024-08-30 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0038_remove_exercise_lesson_exercise_no_exercise_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='no',
            field=models.BigIntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='no',
            field=models.BigIntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='section',
            name='component_quantity',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='section',
            name='no',
            field=models.BigIntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='topic',
            name='no',
            field=models.BigIntegerField(default=-1),
        ),
    ]
