# Generated by Django 5.0.7 on 2024-08-30 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0039_alter_chapter_no_alter_lesson_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animation',
            name='no',
            field=models.BigIntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='content',
            name='no',
            field=models.BigIntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='no',
            field=models.BigIntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='image',
            name='no',
            field=models.BigIntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='section',
            name='component_quantity',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
