# Generated by Django 5.0.7 on 2024-09-06 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0043_lesson_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='height',
            field=models.PositiveBigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='image',
            name='width',
            field=models.PositiveBigIntegerField(default=1),
        ),
    ]
