# Generated by Django 5.0.7 on 2024-09-08 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0044_image_height_image_width'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['no']},
        ),
        migrations.AddField(
            model_name='course',
            name='no',
            field=models.BigIntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
    ]
